### ISSUE TITLE
Please tag a release for MELPA-stable

### ISSUE THREAD

**Issue by rnkn** [joddie/osx-clipboard-mode#1]
Nice work. For those of us only using [MELPA-stable](https://stable.melpa.org), if you could please make your package available:

From https://github.com/melpa/melpa#contributing-new-recipes:

> - To have a stable version generated for your package simply tag the repository using a naming compatible with `version-to-list`. The repo state of this tag will be used to generate the stable package.

**Comment by joddie** [comment]
Done, thanks for the suggestion.  Was there a blog post or something about this recently?  Just curious since I got similar PRs on two other repos about the same time.

**Comment by rnkn** [comment]
Thanks. Not that I know of. I just stumbled upon randomly.
