### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by rnkn** [joddie/osx-clipboard-mode#2]
I'm only half trolling, but with the next version of OS X dropping the X in favour of macOS Sierra, might be worth changing the name to `ns-clipboard-mode`... 😉

**Comment by joddie** [comment]
Ha, not a bad idea. `macos-` or `mac-clipboard-mode` is also a possibility. My only concern is that Emacs has builtin variables of its own beginning both `ns-` and `mac-`. I'll think about it a bit more.
